version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - environment: environment.yml
  post-install:
    - python -m kenazlbm.prefetch_models

