version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Prefetch pretrained models after environment is ready
    - python -c "from kenazlbm.core import prefetch_models; prefetch_models()"

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml
