# environment.yml
name: lbm_env
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.3
  - scipy=1.12.0
  - scikit-learn
  - matplotlib=3.8.2
  - pandas=2.5.1
  - seaborn=0.13.2
  - joblib=1.3.2
  - pip=23.3.1
  - pip:
      - git+https://github.com/grahamwjohnson/KenazLBM.git#egg=kenazlbm
      - torchinfo==1.8.0
      - torch==2.8.0
      - sphinx
      - sphinx-rtd-theme
      - myst-parser