# environment.yml
name: kenazlbm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - joblib
  - pip
  - pip:
      - git+https://github.com/grahamwjohnson/KenazLBM.git#egg=kenazlbm
      - torchinfo
      - sphinx
      - sphinx-rtd-theme
      - myst-parser