# environment.yml
name: lbm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip=23.3.1
  - pip:
      - git+https://github.com/grahamwjohnson/KenazLBM.git#egg=kenazlbm
      - torchinfo==1.8.0
      - torch==2.8.0
      - joblib==1.3.2
      - numpy==1.26.3
      - pandas==2.0.3
      - matplotlib==3.8.2
      - seaborn==0.13.2
      - scipy==1.12.0
      - scikit-learn==1.4.0
      - sphinx
      - sphinx-rtd-theme
      - myst-parser
      - pyedflib==0.1.32