name: kenazlbm
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.12
  - pip

  # Scientific stack
  - numpy
  - scipy
  - pytorch

  # (Optional but common scientific libs you might use)
  - pandas
  - matplotlib

  # Install your project itself via pip
  - pip:
      - -e .          # editable install of your repo
      # Docs dependencies
      - sphinx
      - sphinx-rtd-theme
      - myst-parser
      # Dev/test dependencies
      - pytest
      - black
      - ruff
