# environment.yml
name: kenazlbm
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pytorch
  - pip:
      - git+https://github.com/grahamwjohnson/KenazLBM.git#egg=kenazlbm
      - sphinx
      - sphinx-rtd-theme
      - myst-parser

# Run the post-install script to cache pretrained models
# (Works on Binder/Repo2Docker or manual run: conda env create ... && ./postBuild)
postBuild:
  - python scripts/prefetch_models.py