# environment.yml
name: kenazlbm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pytorch
  - pip:
      - git+https://github.com/grahamwjohnson/KenazLBM.git#egg=kenazlbm
      - sphinx
      - sphinx-rtd-theme
      - myst-parser
